### ISSUE TITLE
[Feature request] Add ability to sign for longer periods of time (1 hour, 8 hours?)

### ISSUE THREAD

**Issue by pleblira** [diegogurpegui/nos2x-fox#10]
It would be nice to have the ability to sign for periods longer than 5 minutes. 

I don't want to sign forever, but feel the 5 minute period is too short and have to keep on signing multiple times.

My suggestion would be 1 hour, and 8 hours.

Thanks!

**Comment by diegogurpegui** [comment]
Sounds good! I'll keep in my TODO list.
Thanks!

**Comment by diegogurpegui** [comment]
Done!
Included in the version 1.10.0 available thru Firefox add-ons page or here: https://github.com/diegogurpegui/nos2x-fox/releases/tag/v1.10.0
