### ISSUE TITLE
[FEATURE REQUEST] Private Key Masking

### ISSUE THREAD

**Issue by crimsonleaf363** [diegogurpegui/nos2x-fox#17]
**Description**:

Mask the nsec behind circle bullets as entered by the user

**Current behavior**:

The nsec is only masked after it's been saved

**Expected behavior**:

User doesn't expose their nsec to prying eyes or cameras

**Comment by diegogurpegui** [comment]
Makes sense. We could implement the classical "eye" icon on passwords inputs.

**Comment by diegogurpegui** [comment]
Done! Included in version [v1.14.0](https://github.com/diegogurpegui/nos2x-fox/releases/tag/v1.14.0)
