### ISSUE TITLE
Permissions not showing in Options

### ISSUE THREAD

**Issue by diegogurpegui** [diegogurpegui/nos2x-fox#19]
The Permissions are not showing in the Options page. It was working before but got broken with the multi-profile feature.
It's probably because they are not being saved along with the problem by mistake, then not properly retrieved. Or a similar bug.

**Comment by xeruf** [comment]
Yep, which means they cannot be revoked and I cannot easily change my account on an instance once authorized.
Would highly appreciate a fix.

**Comment by diegogurpegui** [comment]
Already fixed in latest version 1.13.0. Already available in the marketplace or for self installation.
https://github.com/diegogurpegui/nos2x-fox/releases/tag/v1.13.0
