### ISSUE TITLE
Unable to Export profile

### ISSUE THREAD

**Issue by tmoody** [diegogurpegui/nos2x-fox#22]
Ubuntu (Jammy), Firefox 119.0

When choosing to 'Export profile', an overlay is displayed but it is width-restricted, preventing proper display of the content or the ability to proceed within the Profile section beyond that point:

![image](https://github.com/diegogurpegui/nos2x-fox/assets/79837106/926455f7-5118-425c-b1cb-eda112fa609f)

**Comment by diegogurpegui** [comment]
Thanks for reporting!

**Comment by diegogurpegui** [comment]
Already fixed in latest version 1.13.0. Already available in the marketplace or for self installation.
https://github.com/diegogurpegui/nos2x-fox/releases/tag/v1.13.0
