### ISSUE TITLE
will this be available for android?

### ISSUE THREAD

**Issue by melvincarvalho** [diegogurpegui/nos2x-fox#27]
Firefox android launching December 14 (tomorrow)

https://blog.mozilla.org/addons/2023/11/28/open-extensions-on-firefox-for-android-debut-december-14-but-you-can-get-a-sneak-peek-today/

**Comment by diegogurpegui** [comment]
That's great news!
I'll check if there's something to adjust to make it available for Firefox. I tried a while back and made it work, but that was when everything was beta.

**Comment by melvincarvalho** [comment]
Blog post about it [here](https://blog.mozilla.org/addons/2023/12/14/a-new-world-of-open-extensions-on-firefox-for-android-has-arrived/)

With [starting point for developing extensions for Firefox for Android](https://extensionworkshop.com/documentation/develop/developing-extensions-for-firefox-for-android/)

**Comment by diegogurpegui** [comment]
Done! The new version 1.13.0 is already available in the Mozilla Firefox marketplace.

**Comment by melvincarvalho** [comment]
Awesome, thanks!  Can be tested with:

https://nostrapps.github.io/login/
