### ISSUE TITLE
Name a Profile

### ISSUE THREAD

**Issue by crimsonleaf363** [diegogurpegui/nos2x-fox#29]
### **Problem**

Public key strings can be difficult to read, especially if you're managing multiple keys. 

### **Proposed Solution**

Provide the option to name a profile, which would be easier to recognize than just an npub. Users could also view the name alongside the shortened public key for a better overall usability. 

- Users can name their profile during the key generation process or later on by editing the profile in options.
- When exporting a profile, users can choose a custom file name that includes both the profile name and the associated npub (e.g., "Custom Profile Name (npub...xyz)").

**Comment by diegogurpegui** [comment]
Done! Included in version [v1.14.0](https://github.com/diegogurpegui/nos2x-fox/releases/tag/v1.14.0)
