### ISSUE TITLE
Does nos2x-fox accept nsec format?

### ISSUE THREAD

**Issue by pleblira** [diegogurpegui/nos2x-fox#3]
Hey there,

I'm trying to add an nsec key I generated on Damus to my nos2x-fox, but I'm getting a "the key is not valid error". 

Does the extension accept nsec or just hex format keys?

I might be doing something wrong.

Thank you,

**Comment by diegogurpegui** [comment]
Hey!
No, the extension is not supporting nsec key format, only hexadecimal. But nice suggestion, I'll look into it.

**Comment by pleblira** [comment]
Sounds great, thank you.

In the meanwhile, I converted it to hex using a different tool and the extension is working great on Firefox. Thanks!

**Comment by takedawilliam** [comment]
> In the meanwhile, I converted it to hex using a different tool and the extension is working great on Firefox. Thanks!

How do you convert to hex format?

https://github.com/diegogurpegui/nos2x-fox/issues/3#issuecomment-1400525695

**Comment by diegogurpegui** [comment]
This was included in the latest version v1.8.0 (https://github.com/diegogurpegui/nos2x-fox/releases/tag/v1.8.0)
Any feedback is appreciated!
