### ISSUE TITLE
Add nip44 support

### ISSUE THREAD

**Issue by abhay-raizada** [diegogurpegui/nos2x-fox#32]
Add nip44 support as mentioned in the upgraded in nip07: https://github.com/nostr-protocol/nips/blob/master/07.md

and as also present in in the chrome nos2x extension: https://github.com/fiatjaf/nos2x/blob/master/extension/nostr-provider.js#L29

**Comment by diegogurpegui** [comment]
Good call, I'll look into it.

**Comment by diegogurpegui** [comment]
Done! Included in version [v1.14.0](https://github.com/diegogurpegui/nos2x-fox/releases/tag/v1.14.0)
