### ISSUE TITLE
Throw error when event pubkey does not match

### ISSUE THREAD

**Issue by rossbates** [diegogurpegui/nos2x-fox#37]
Curious to learn what the expected behavior here is. In my client I'm generating an unsigned event with the id and pubkey populated and then using window.nostr.signEvent().

When the nos2x-fox keypair matches the event pubkey everything works great. During testing I added a second profile to test failure states in the UI, to my surprise the extension modified the event with a new id and pubkey and generated a valid sig.

I can deal with this client side by comparing window.nostr.getPublicKey() to the event pubkey, but this was surprising that the extension would change the pubkey instead of throwing an error.

If someone were using multiple profiles on a web client it seems like they could accidentally publish content under the wrong username without warning.

**Comment by diegogurpegui** [comment]
That's a good catch! The extension should raise a warning on those cases. I'll look into it (or anyone reading this can create a PR :stuck_out_tongue: ).

PS: sorry for the delay in the response, I somehow missed the notification

**Comment by diegogurpegui** [comment]
This was already fixed and just included in the new release [v0.15.0](https://github.com/diegogurpegui/nos2x-fox/releases/tag/v0.15.0).
If the pubkeys don't math it now throws an error.

Let me know if you find any issue.
