### ISSUE TITLE
Forefox

### ISSUE THREAD

**Issue by suddenwhipvapor** [diegogurpegui/nos2x-fox#38]
Elephant in the room I know... but I just searched in the issues, and no such thing has been reported yet.
The "Forefox" prominently placed in the README and not yet fixed looks ominous for a project that is expected to hold a private key 😅 
No drama intended!

**Comment by diegogurpegui** [comment]
OMG! I don't know how that could be there for so long :man_facepalming: 
Thank you pointing that out. Fixed now.

Thankfully the project is open source and you can see how the private keys are handled :sweat_smile:
