### ISSUE TITLE
[Feature Request] Preferred relays

### ISSUE THREAD

**Issue by Sakhalinfox** [diegogurpegui/nos2x-fox#4]
Preferred relays configurable by the user on the extension could allow the user to define a map of some relays, so that when they login to web clients and if clients request for the relay list, maybe they could be sent after the user authorizes it. 

According to NIP-07 `async window.nostr.getRelays(): { [url: string]: {read: boolean, write: boolean} } // returns a basic map of relay urls to relay policies`

This is currently available with [Nos2x](https://github.com/fiatjaf/nos2x/commit/414c0ea3373d1f50b22a29872bd29ff8eb729791) and maybe could be implemented or forked here as well?

**Comment by diegogurpegui** [comment]
Sounds good!
This was forked from nos2x a few weeks back and that feature seems to be there for almost a year. But I know the Firefox branch was not maintained so that would explain why the feature is not included.
I'll add to to my TODO list, thanks!

**Comment by Sakhalinfox** [comment]
> Sounds good! This was forked from nos2x a few weeks back and that feature seems to be there for almost a year. But I know the Firefox branch was not maintained so that would explain why the feature is not included. I'll add to to my TODO list, thanks!

Sounds good, thank you!

**Comment by diegogurpegui** [comment]
This was included in the latest version v1.8.0 (https://github.com/diegogurpegui/nos2x-fox/releases/tag/v1.8.0)
Any feedback is appreciated!
