### ISSUE TITLE
Version 0.15.0 does not work with primal web, it does not sign events.

### ISSUE THREAD

**Issue by x86-x86** [diegogurpegui/nos2x-fox#40]
Version 0.15.0 does not work with primal web, it does not sign events.

The previous version 1.14.0 (I don't know why it has different numbering) works correctly.

**Comment by laanwj** [comment]
Noticed the same problem: nostrudel cannot zap anymore, nostter doesn't sign events at all anymore.

**Comment by lescuer97** [comment]
Same with signing on a local website of mine

**Comment by lescuer97** [comment]
I'm getting the error from this commit: https://github.com/diegogurpegui/nos2x-fox/commit/dc983dd7d7b083997b5272b241e14a88d5573acf.

**Comment by diegogurpegui** [comment]
I'll look into it asap. It might be due to some sites wanting to sign events without specifying the public key. I'll check and push a fix asap.

**Comment by diegogurpegui** [comment]
Done, fixed in [v1.16.0](https://github.com/diegogurpegui/nos2x-fox/releases/tag/v1.16.0)

Thanks for reporting! And let me know if you find any other bug.
