### ISSUE TITLE
[Feature Request] Revoke permissions

### ISSUE THREAD

**Issue by Sakhalinfox** [diegogurpegui/nos2x-fox#5]
For authorizations to events that have been approved by the user, it would be nice to have a 'Revoke' option in the options page that would revoke the authorization by clearing out the permissions in local storage.

This is implemented in [Nos2x](https://github.com/fiatjaf/nos2x/commit/1fd5c6ba96e216ff5826a0e11bf8668e6b731ad2) and maybe can be forked?

**Comment by diegogurpegui** [comment]
Sure! Thanks for the input. Will do it.

**Comment by diegogurpegui** [comment]
This was included in the latest version v1.8.0 (https://github.com/diegogurpegui/nos2x-fox/releases/tag/v1.8.0)
Any feedback is appreciated!
