### ISSUE TITLE
[Feature Request] Mask or hide private keys

### ISSUE THREAD

**Issue by Sakhalinfox** [diegogurpegui/nos2x-fox#6]
Add a feature to mask the private key visibility with an asterisk `*` or a dot `●`.  This way if we open the options page to revoke permissions to configure something, it's not open for viewing when in a public area.

**Comment by diegogurpegui** [comment]
Sounds like a good idea. Thanks for the feedback!

**Comment by diegogurpegui** [comment]
This was included in the latest version v1.8.0 (https://github.com/diegogurpegui/nos2x-fox/releases/tag/v1.8.0)
Any feedback is appreciated!

**Comment by Sakhalinfox** [comment]
Much appreciated! Thank you it looks good!
