### ISSUE TITLE
[Feature Request] Add support for setting up multiple profiles keypair

### ISSUE THREAD

**Issue by Sakhalinfox** [diegogurpegui/nos2x-fox#7]
It would be nice to configure multiple profiles consisting of the private/public keypair and allow the user to select which profile that they would want to authorize with while using Nostr Clients. 

A selection dropdown in the options page for creating profiles and selecting would be useful. Once a new profile is selected, the 'generate' option would be present to create a new keypair and save it or the user can save their own. Selecting another profile from the dropdown would display another keypair. 

The profiles should also allow individually setting up different preferred relays..etc. Basically all options should fall under individual profiles to configure independently per profile. 

During authorization prompt the user could be provided the option to select from the list of setup profiles to authorize from. A default or primary profile could be provided as an option too, or default to the value of the previous profile from which authorization was done. 

Also, provide an option to delete profiles with a warning message to backup the private key.

**Comment by diegogurpegui** [comment]
This sounds like and interesting feature to have.
I'm wondering if it makes sense for the user to select the profile each time it has to authorize something. I'm thinking that, in term of UX, it would be better to just select the "Active profile" at the extension level and operate with that until you change it.
I see the scenario of someone switching from one account to other from time to time, more common than someone operating with more than one profile at the same time.

**Comment by Sakhalinfox** [comment]
> This sounds like and interesting feature to have. I'm wondering if it makes sense for the user to select the profile each time it has to authorize something. I'm thinking that, in term of UX, it would be better to just select the "Active profile" at the extension level and operate with that until you change it. I see the scenario of someone switching from one account to other from time to time, more common than someone operating with more than one profile at the same time.

Yes, I think I agree with that. To keep things simple, maybe it's good to default to a selected profile, until the user changes it in the extension options. Then the authorizations would switch to the new selection.

**Comment by diegogurpegui** [comment]
Thanks for the input @Giszmo !
Storing the last used profile per domain is an interesting addition, will keep it in mind.

Regarding the pull from multiple accounts, as you said that requires a proper new API and the clients to support it. I think it's more of a niche use case, so I'm not sure if it will have enough adoption.

**Comment by Giszmo** [comment]
I was working on nostroid which was from the start meant to work with multiple accounts and just like Twitter it would tell you if there were notifications on your other accounts.

If Twitter is the benchmark, this is not as niche as you might think but I have no numbers on how many accounts are secondary accounts or how many users use Twitter with more than one account. Twitter would certainly know.

**Comment by diegogurpegui** [comment]
This was included in version 1.12.0 (https://github.com/diegogurpegui/nos2x-fox/releases/tag/v1.12.0)
