### ISSUE TITLE
Install on Firefox mobile

### ISSUE THREAD

**Issue by hannpet** [diegogurpegui/nos2x-fox#8]
Is there any way to install the Addon in the mobile version of Firefox?
If not, it would be a very much needed feature 👍

**Comment by diegogurpegui** [comment]
I've been thinking about this for a while but never prioritize it because for Android it's better to just use the native apps.
But since you already created the PR, I'll take a look.

**Comment by diegogurpegui** [comment]
This was released in version 1.11.0
https://github.com/diegogurpegui/nos2x-fox/releases/tag/v1.11.0
